### ISSUE TITLE
After 3 days, noway to make it working, help !

### ISSUE THREAD

**Issue by Schlag-vuk** [coccyx/eventgen#18]
Dear all,

I downloaded the "eventgen-master.zip" version and unzipped it to $splunk\etc\apps\eventgen
Eventgen app permissions is set to global.
Data input SA-Eventgen is present.

I created a new app called "myloggenerator" with a global permission set to global.
I copied the "sample.tutorial1" file to myloggenerator/local/sample.tutorial1
I copied the "eventgen.conf.tutorial1" file to myloggenerator/local/samples/eventgen.conf

After a splunkd restart the only thing that I can see in the eventgen logs is : 
=> Creating timer object for sample 'sample.tutorial1' in app 'myloggenerator' 
=> Starting timer for sample 'sample.tutorial1'

In the Splunk logs I have : 
=> 2018-05-07 11:22:22,099 WARNING module='Output' sample='sample.tutorial1': Output Queue full, looping again

What is wrong here ?

Cheers

**Comment by coccyx** [comment]
This project is now maintained by Splunk at https://github.com/splunk/eventgen. They're multiple versions ahead of this project. I'd recommend trying there.
